root: true

env:
  browser: true
  jest: true

extends:
  - airbnb
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:react/jsx-runtime
  - plugin:jsx-a11y/recommended
  - plugin:import/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended

plugins:
  - '@typescript-eslint'

parser: '@typescript-eslint/parser'

parserOptions:
  sourceType: 'module'
  project: './tsconfig.json'

settings:
  import/extensions:
    - .js
    - .jsx
    - .ts
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts

rules:
  import/no-cycle: [2, { maxDepth: 1 }]
  import/prefer-default-export: 0
  import/extensions: 0
  no-console: 0
  react/prop-types: 'off'
  consistent-return: 0
  react/jsx-sort-props: 1
  '@typescript-eslint/interface-name-prefix': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  'click-events-have-key-events': 'off' # не знал как исправить в компоненте "/FileTree/Directory.jsx"
