FROM node:23


RUN apt update && apt install -y make curl

ENV DOCKER_CHANNEL stable
ENV DOCKER_VERSION 20.10.21

RUN curl -fsSL "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/x86_64/docker-${DOCKER_VERSION}.tgz" \
| tar -xzC /usr/local/bin --strip=1 docker/docker

WORKDIR /usr/src/runit

COPY . .

RUN make setup

CMD [ "make", "start-prod" ]
