name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment stub
        run: |
          echo "🚧 Deployment is temporarily disabled"
          echo "This is a stub to prevent job failure"
          echo "Tag: ${{ github.ref_name }}"
          echo "Repository: ${{ github.repository }}
          
# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - uses: actions/setup-node@v3
#       with:
#         node-version: "22"
#     - name: Install dependencies
#       run: make setup
#     - name: Install Playwright Browsers
#       run: npx playwright install --with-deps
#     - name: Build
#       run: make build
#     - name: Run Playwright tests
#       run: npm run test:ci
#     - uses: actions/upload-artifact@v4
#       if: always()
#       with:
#         name: playwright-report
#         path: playwright-report/
#         retention-days: 30

#     - uses: daun/playwright-report-summary@v3
#       if: always()
#       with:
#         report-file: results.json
